mode_topic: "fsm_node/mode"
source_topics: #Mapping from cmd source name to topics
  lane: "lane_controller_node/car_cmd"
  joystick: "joy_mapper_node/car_cmd"
  stop: "simple_stop_controller_node/car_cmd"
  avoid: "avoiders_controller_node/car_cmd"

mappings: #Mapping from FSMStates.state to cmd source names. Allows different FSM mode to use the same source.
  LANE_FOLLOWING: "lane"
  STOP_AT_INTERSECTION: "stop"
  COMM_AT_INTERSECTION: "stop"
  NAVIGATE_INTERSECTION: "lane" #LP: this seems weird
  AVOID_OBSTACLES: "avoid"
  NORMAL_JOYSTICK_CONTROL: "joystick"